version: '3'
services:
  backend:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
